global:
  environment: prod

namespace: prod

image:
  registry:    acremployeedirprod.azurecr.io
  tag:         v1-prod

replicaCount:
  backend:  2
  frontend: 2

postgres:
  storage: 5Gi

resources:
  backend:
    requests:
      memory: "512Mi"
      cpu:    "500m"
    limits:
      memory: "1Gi"
      cpu:    "1000m"
  frontend:
    requests:
      memory: "256Mi"
      cpu:    "200m"
    limits:
      memory: "512Mi"
      cpu:    "400m"