apiVersion: v1
kind: Secret
metadata:
  name: employee-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app : employee-directory
    environment: {{ .Values.global.environment }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote}}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host}}:5432/{{ .Values.postgres.db }}"
